---
title: "Assess causality"
output: html_notebook
---




```{r setup, class.source='fold-show'}
rm(list = ls())

library(tidyverse)
library(progress)
library(foreach) # for parallel computing
library(doParallel) # for parallel computing
library(ggplot2)
library(ggrepel) # for labels on ggplots (like geom_text_repel)

library(rEDM) # For Empircal dynamic modeling (simplex, CCM, block_lnlp...)

```


# Parameters

## Input information

```{r parameters_input}
# path_dataframe_input = "data/RAM_timeseries_clean-light.csv"
path_dataframe_input = "data/RAM_timeseries_clean.csv"
# path_dataframe_input = "data/20241029-RAM_timeseries_clean-prod_and_recruitment.csv"

df = read.csv(path_dataframe_input)

name_id_timeseries = "stockid"
name_time = "year"

# list_of_causality_tested  = list(
#   # c(cause, consequence)
#   c("sst.z", "prodbest.div"), 
#   c("UdivUmsypref", "prodbest.div"),
#   c("prodbest.div", "sst.z"),
#   c("prodbest.div", "UdivUmsypref")
# )

list_of_causality_tested  = list(
  # c(cause, consequence)
  # c("sst.z", "R"), 
  # c("UdivUmsypref", "R"),
  # c("R", "sst.z"),
  # c("R", "UdivUmsypref"),
  
  c("sst.z", "prodbest.div"),
  c("UdivUmsypref", "prodbest.div"),
  c("prodbest.div", "sst.z"),
  c("prodbest.div", "UdivUmsypref")#,
  
  # c("prodbest.div", "R"),
  # c("R", "prodbest.div")
)

labels_of_variables = c(
  "sst.z" = "SST", 
  "prodbest.div" = "Surplus of productivity", 
  "UdivUmsypref" = "Harvest rate",
  "R" = "Recruitment"
)


# IDs that will be used for computations
# all_ids = df %>% pull(all_of(name_id_timeseries)) %>% unique()
all_ids = df %>% 
  group_by_at(vars(all_of(name_id_timeseries))) %>%
  summarise(n = n()) %>%
  filter(n >= 40) %>%
  pull(all_of(name_id_timeseries)) %>% unique()

# IDs that will be used for plots (it could be modified later in the script)
all_ids_plots = df %>% 
  group_by_at(vars(all_of(name_id_timeseries))) %>%
  summarise(n = n()) %>%
  filter(n >= 40) %>%
  pull(all_of(name_id_timeseries)) %>% unique()

# IDs for plots with a single ID
ids_single_plots = c("CALSCORPSCAL", "CHROCKSPCOAST", "BRNROCKPCOAST")


```


## Execution parameters

```{r parameters_exe}
# Parameters for the EDM
E_tested_simplex = 2:10 # embedding dimensions tested in the simplex projection (and used in CCM)
methods_select_E = list("max_rho" = TRUE, "positive_range_top_x_percent" = c(0.2)) # methods to select the embedding dimension
method_select_E_prefered = "positive_range_top_20_percent"
method_select_E_default = "max_rho" # if the prefered method provides NA

tp_tested_simplex = 1:10 # time horizon for prediction tested in the simplex projection
# theta_tested_smap = seq(0, 8, by = 0.4) # non-linearity theta tested in the s-map
# tp_tested_causality = c(0, -5:-1, 1:5) # time horizon for prediction tested in CCM
tp_tested_causality = 0 # time horizon for prediction tested in CCM
methods_strength = c("Smap_Edim_space") # methods to assess the strength of the causality 
# within c("CCM_max_rho", "CCM_rate_incr_rho", "CCM_AUC", "Smap_Edim_space", "Smap_pair_space", "Smap_full_space")

# Step executed
exe_simplex_tp1 = FALSE # Simplex projection along E_tested_simplex and with tp = 1 -> assess the optimal embedding dimension
exe_ccm_best_E_and_tp = FALSE # CCM with the best E along tp_tested_causality -> compute the CCM and assess the causality
exe_strength_causality = FALSE # Assess the strength of the causality
exe_granger_causality = FALSE # Assess the Granger causality
```


## Output information

```{r parameters_output}
dir_out = "out/20241124-prod_SST_U/"
# dir_out = "out/20241029-full-prod_and_recruitment/"

file_save_out_simplex_tp1 = paste0(dir_out, "computations/01_a-out_simplex_tp1.csv")
file_save_out_simplex_tp1_summary_opti_E = paste0(dir_out, "computations/01_b-out_simplex_tp1_summary_opti_E.csv")

file_save_out_ccm_best_E_and_tp_summaries = paste0(dir_out, "computations/02_a-out_ccm_best_E_and_tp-summaries.csv")
file_save_out_ccm_best_E_and_tp_assessment = paste0(dir_out, "computations/02_b-out_ccm_best_E_and_tp-assessment.csv")
file_save_out_strength_causality = paste0(dir_out, "computations/03_a-out_strength_causality.csv")
file_save_out_strength_causality_details_smap = paste0(dir_out, "computations/03_b-out_strength_causality_details_smap.csv")

file_save_out_granger_causality = paste0(dir_out, "computations/04_a-out_granger_causality.csv")
file_save_out_granger_causality_details = paste0(dir_out, "computations/04_b-out_granger_causality_details.csv")

exe_plots = TRUE
save_plots = TRUE
plots_with_titles = FALSE
types_plots = c("pdf", "png")


# Set up the output directories
if (!dir.exists(dir_out)) dir.create(dir_out) # Create the output directory
if (save_plots) { 
  for (typ in types_plots) { 
    if (!dir.exists(paste0(dir_out, typ))) {
      dir.create(paste0(dir_out, typ)) # Create the directories for each type of plot
    }
  }
}
# Create the directory where we store the outputs of the computations
if (!dir.exists(paste0(dir_out, "computations/"))) dir.create(paste0(dir_out, "computations/")) 

```



# Utils functions

```{r utils_functions}

source("utils/01-get_optimal_E_simplex.R")
source("utils/02-CCM_and_tests.R")
source("utils/03-strength_of_causality_smap.R")
source("utils/04-granger_causality_test.R")

source("utils/plots_timeseries.R")
source("utils/plots_rEDM.R")


# Function to save the outputs, either csv, rds, or RData files
save_file = function(object, path_file) {
  
  if (file.exists(path_file)) {
    warning("The file ", path_file, " already exists... It will be overwritten.")
  }
  
  if (grepl(".csv", path_file)) { # CSV file
    write.csv(object, path_file, row.names = FALSE)
  } else if (grepl(".RData", path_file)) { # RData file
    save(object, file = path_file)
  } else if (grepl(".rds", path_file)) { # RDS file
    saveRDS(object, file = path_file)
  } else {
    stop("The file ", path_file, " is not a csv or RData file.")
  }
  
}

# Function to import either csv, rds, or RData files
import_file = function(path_file) {
  
  if (!file.exists(path_file)) {
    warning("The file ", path_file, " does not exist... The function returns NULL.")
    return(NULL)
  } 
  
  if (grepl(".csv", path_file)) { # CSV file
    return(read.csv(path_file))
  } else if (grepl(".RData", path_file)) { # RData file
    load(path_file)
    return(get(ls()[ls() != "path_file"]))
  } else if (grepl(".rds", path_file)) { # RDS file
    return(readRDS(path_file))
  } else {
    stop("The file ", path_file, " is not a csv or RData file.")
  }
  
}

```



# Plots dataset

```{r plots_dataset}

if (exe_plots) {
  
  # Durations of the timeseries histogram
  p.fig1a = ggplot_timeseries_durations_hist(df %>% filter( .data[[name_id_timeseries]] %in% all_ids_plots),
                                             name_id_timeseries, time = name_time)
  if (!plots_with_titles) p.fig1a = p.fig1a + labs(title = NULL, subtitle = NULL)
  print(p.fig1a)
  
  # Durations of the timeseries
  p.figS1 = ggplot_timeseries_durations(df %>% filter( .data[[name_id_timeseries]] %in% all_ids_plots),
                                        name_id_timeseries, time = name_time, size_y_axis = 4)
  if (!plots_with_titles) p.figS1 = p.figS1 + labs(title = NULL, subtitle = NULL)
  print(p.figS1)
  
  # Pie chart of the regions
  p.fig1b = ggplot_timeseries_piechart(df %>% filter( .data[[name_id_timeseries]] %in% all_ids_plots),
                                       name_id_timeseries, "region", labels_of_variable = "Regions", 
                                       size_legend = 7)
  if (!plots_with_titles) p.fig1b = p.fig1b + labs(title = NULL, subtitle = NULL)
  print(p.fig1b)
  
  # Timeseries for 1 stock
  variables = unique(unlist(list_of_causality_tested))
  lst_p.fig1c = list()
  # this_id.p.fig1c = all_ids[1]
  for (this_id.p.fig1c in ids_single_plots) {
    p.fig1c = ggplot_timeseries_one_stock(df[df[[name_id_timeseries]] == this_id.p.fig1c, ], variables, 
                                          labels_of_variables, id = this_id.p.fig1c, time = name_time, scale = TRUE)
    if (!plots_with_titles) p.fig1c = p.fig1c + labs(title = NULL, subtitle = NULL)
    print(p.fig1c)
    lst_p.fig1c[[this_id.p.fig1c]] = p.fig1c
  }
  
  # Save the plots
  if (save_plots) {
    for (typ in types_plots) {
      ggsave(p.fig1a, filename = paste0(dir_out, typ, "/fig1a-timeseries_durations_hist.", typ), device = typ,
             width = 4, height = 3)
      ggsave(p.figS1, filename = paste0(dir_out, typ, "/figS1-timeseries_durations.", typ), device = typ,
             width = 6, height = 8)
      ggsave(p.fig1b, filename = paste0(dir_out, typ, "/fig1b-timeseries_piechart_region.", typ), device = typ,
             width = 7, height = 5)
      for (this_id.p.fig1c in ids_single_plots) {
        ggsave(lst_p.fig1c[[this_id.p.fig1c]], 
               filename = paste0(dir_out, typ, "/fig1c-timeseries_one_stock-", this_id.p.fig1c, ".", typ), device = typ,
               width = 6, height = 3.5)
      }
    }
  }
  
}

```





# Estimate the optimal embedding dimension

## Computations

```{r simplex_projection}
if (exe_simplex_tp1) {
  
  cat(" * * * Simplex projection tp = 1 * * *\n-> assess the optimal embedding dimension with a time horizon = 1\n")
  
  
  # / * / * / * APPLY THE SIMPLEX PROJECTION * \ * \ * \
  cat("Apply the simplex projection...\n")
  
  df_input_simplex = expand.grid(
    id_timeseries = all_ids, 
    variable = unique(sapply(list_of_causality_tested, function(x) x[2])) # consequence variables will be libraries
  )
  
  pb = progress::progress_bar$new(format = "[:bar] :percent eta: :eta", total = nrow(df_input_simplex))
  
  # Without parallel computing
  res_simplex_tp1 = data.frame()
  for (i in 1:nrow(df_input_simplex)) {
    
    this_id <- df_input_simplex$id_timeseries[i]
    this_var <- as.character(df_input_simplex$variable[i])
    this_df <- df[df[[name_id_timeseries]] == this_id, c(name_time, this_var)]
    # Scale the variable (even if it's already done in this version of simplex projection)
    this_df[[this_var]] <- scale(this_df[[this_var]])[, 1]
    
    # Apply the simplex projection
    out_simp <- simplex(this_df[[this_var]], E = E_tested_simplex, tp = 1, 
                        silent = TRUE, stats_only = TRUE)
    
    res_simplex_tp1 <- res_simplex_tp1 %>% rbind(
      data.frame(variable = this_var, id_timeseries = this_id, out_simp)
    )
    
    pb$tick()
  }
  
  # # With parallel computing
  # # Prepare parallel computing
  # num_cores <- detectCores()
  # cl <- makeCluster(num_cores)
  # registerDoParallel(cl)
  # clusterExport(cl, "pb") # Export the progress bar to the parallel backend
  # 
  # # Apply the simplex projection in parallel
  # res_simplex_tp1 <- foreach(i = 1:nrow(df_input_simplex), .combine = rbind, .packages = 'rEDM') %dopar% {
  #   
  #   tryCatch(pb$tick(), error = function(e) NULL) # Update the progress bar
  #   
  #   this_id <- df_input_simplex$id_timeseries[i]
  #   this_var <- as.character(df_input_simplex$variable[i])
  #   this_df <- df[df[[name_id_timeseries]] == this_id, c(name_time, this_var)]
  #   # Scale the variable (even if it's already done in this version of simplex projection)
  #   this_df[[this_var]] <- scale(this_df[[this_var]])[, 1]
  #   
  #   # Apply the simplex projection
  #   out_simp <- simplex(this_df[[this_var]], E = E_tested_simplex, tp = 1, 
  #                       silent = TRUE, stats_only = TRUE)
  #   
  #   data.frame(variable = this_var, id_timeseries = this_id, out_simp)
  # }
  # 
  # # Stop the parallel backend when done
  # stopCluster(cl)
  
  save_file(res_simplex_tp1, file_save_out_simplex_tp1)
  
  
  
  
  # / * / * / * SUMMARY OF THE OPTIMAL EMBEDDING DIMENSION * \ * \ * \
  cat("Summary of the optimal embedding dimension...\n")
  
  res_simplex_tp1_summary_opti_E = data.frame()
  
  for (i in 1:nrow(df_input_simplex)) {
    
    this_id <- df_input_simplex$id_timeseries[i]
    this_var <- as.character(df_input_simplex$variable[i])
    this_res_simp <- res_simplex_tp1 %>% filter(id_timeseries == this_id, variable == this_var)
    
    out_opti_E = get_optimal_E_simplex(this_res_simp, methods_select_E = methods_select_E)
    
    res_simplex_tp1_summary_opti_E = res_simplex_tp1_summary_opti_E %>% rbind(
      data.frame(variable = this_var, id_timeseries = this_id, out_opti_E)
    )
    
  }
  
  save_file(res_simplex_tp1_summary_opti_E, file_save_out_simplex_tp1_summary_opti_E)
  
} else {
  
  res_simplex_tp1 = import_file(file_save_out_simplex_tp1)
  res_simplex_tp1_summary_opti_E = import_file(file_save_out_simplex_tp1_summary_opti_E)
  
}

```

## Plots

```{r plots_simplex}

if (exe_plots) {
  # Single id and variable -> rho depending on E
  this_var = as.character(res_simplex_tp1$variable[1])
  lst_p.figS2 = list()
  # this_id.pS2 = all_ids[1]
  for (this_id.p.figS2 in ids_single_plots) {
    p.figS2 = ggplot_simplex_rho_E(res_simplex_tp1, res_simplex_tp1_summary_opti_E, this_id.p.figS2, this_var, labels_of_variables)
    if (!plots_with_titles) p.figS2 = p.figS2 + labs(title = NULL, subtitle = NULL)
    print(p.figS2)
    lst_p.figS2[[this_id.p.figS2]] = p.figS2
  }
  
  # Single variable and method selection E -> histogram of E
  this_method = method_select_E_prefered
  p.figS3 = ggplot_simplex_hist_E(res_simplex_tp1_summary_opti_E %>% filter(id_timeseries %in% all_ids_plots),
                                  this_var, this_method, labels_of_variables)
  if (!plots_with_titles) p.figS3 = p.figS3 + labs(title = NULL, subtitle = NULL)
  print(p.figS3)

  # Save the plots
  if (save_plots) {
    for (typ in types_plots) {
      for (this_id.pS2 in ids_single_plots) {
        ggsave(lst_p.figS2[[this_id.pS2]], 
               filename = paste0(dir_out, typ, "/figS2-simplex_rho_E-", this_id.pS2, ".", typ), device = typ,
               width = 6, height = 4)
      }
      ggsave(p.figS3, filename = paste0(dir_out, typ, "/figS3-simplex_hist_E-", this_var, "-", this_method, ".", typ), device = typ,
             width = 5, height = 4)
    }
  }
  
}

```





# Apply the CCM with the best E and assess the causality


```{r ccm}
if (exe_ccm_best_E_and_tp) {
  
  cat(" * * * CCM with the best E * * *\n-> assess the causality\n")
  
  # Prepare the inputs of the CCM
  
  input.selected.ccm = data.frame()
  for (k in 1:length(list_of_causality_tested)) {
    
    this_var_lib = list_of_causality_tested[[k]][2] # consequence
    this_var_target = list_of_causality_tested[[k]][1] # cause
    
    for (id in all_ids) {
      
      # E is the optimal embedding dimension from the simplex projection with tp = 1... (even if we use it for various tp in the ccm)
      # we could provide multiple E for the function CCM_vs_null, but we will only provide the best one here
      this_E = res_simplex_tp1_summary_opti_E %>% 
        filter(id_timeseries == id, variable == this_var_lib) %>%
        filter(method_E_opti_simplex == method_select_E_prefered) %>%
        pull(E_opti_simplex)
      this_method = method_select_E_prefered
      
      if (is.na(this_E)) { # E with the prefered method can be NA when the forecasting skill is always negative
        this_E = res_simplex_tp1_summary_opti_E %>% 
          filter(id_timeseries == id, variable == this_var_lib) %>%
          filter(method_E_opti_simplex == method_select_E_default) %>%
          pull(E_opti_simplex)
        this_method = method_select_E_default
      }
      
      input.selected.ccm = rbind(input.selected.ccm,
                                 data.frame(id_timeseries = id, 
                                            var_lib = this_var_lib, var_target = this_var_target,
                                            E = this_E, method_E = this_method, 
                                            tp = tp_tested_causality))
    }
  }
  
  # Launch the CCM
  
  res_ccm_best_E_summaries = data.frame()
  res_ccm_best_E_assessment = data.frame()
  pb = progress::progress_bar$new(format = "[:bar] :percent eta: :eta", total = nrow(input.selected.ccm))
  
  for (i in 1:nrow(input.selected.ccm)) {
    
    this_id = input.selected.ccm$id_timeseries[i]
    this_var_lib = input.selected.ccm$var_lib[i]
    this_var_target = input.selected.ccm$var_target[i]
    this_E = input.selected.ccm$E[i]
    this_tp = input.selected.ccm$tp[i]
    
    this_df = df[which(df[[name_id_timeseries]] == this_id), c(name_time, this_var_lib, this_var_target)]
    # Scale the variables (even if it's already done in this version of the ccm)
    for (this_var in c(this_var_lib, this_var_target)) {
      this_df[[this_var]] = scale(this_df[[this_var]])[,1]
    }
    
    this_libs = unique(round(seq(5, nrow(this_df)-this_E, length.out = 20)))
    
    # Apply the CCM
    out_ccm = suppressWarnings(
      CCM_vs_null(this_df, this_var_lib, this_var_target, 
                            E = this_E, libs = this_libs, tp = this_tp,
                            num_boot_origin = 100, num_shuffle_null = 100, rd_seed = NULL,
                            method_shuffle = "keep_correspondance", stats_only = TRUE,
                            quantiles_summary = c(0, 0.05, 0.25, 0.5, 0.75, 0.95, 1))
    )
    
    # Test the causality
    out_test_ccm = test_causality(out_ccm$summary.origin, out_ccm$summary.null, 
                                  val.origin.compare = "rho_50", val.null.compare = "rho_95", val.origin.kendall = "rho_50",
                                  criterium_compare = "90%_above_null", libs_for_crit = NULL,
                                  threshold_p_val_kendall = 0.05, full_output = TRUE, silent = TRUE)
    
    # Store the results (summaries)
    res_ccm_best_E_summaries = res_ccm_best_E_summaries %>% rbind(
      out_ccm$summary.origin %>% 
        add_column(var_lib = this_var_lib, var_target = this_var_target, id_timeseries = this_id, .before = 1) %>%
        add_column(method_E = input.selected.ccm$method_E[i], tp = this_tp, dataset = "origin", .after = 4),
      out_ccm$summary.null %>%
        add_column(var_lib = this_var_lib, var_target = this_var_target, id_timeseries = this_id, .before = 1) %>%
        add_column(method_E = input.selected.ccm$method_E[i], tp = this_tp, dataset = "null", .after = 4)
    )
    
    # Store the results (assessment)
    additionnal_df = data.frame(
      var_lib = this_var_lib, 
      var_target = this_var_target, 
      id_timeseries = this_id, 
      E = this_E,
      method_E = input.selected.ccm$method_E[i],
      tp = this_tp,
      causality = out_test_ccm$causality,
      kendall_tau = out_test_ccm$kendall.tau,
      kendall_p_val = out_test_ccm$kendall.p_val,
      rate.libsizes = mean(out_test_ccm$vect_compare.origin.null),
      max_median_rho_ccm_with_libs = max(out_ccm$summary.origin$rho_50)
    )
    colnames(additionnal_df)[colnames(additionnal_df) == "rate.libsizes"] = 
      paste0("rate.libsizes_", colnames(out_test_ccm$compare.origin.null)[2], "_above_", colnames(out_test_ccm$compare.origin.null)[3])
      
    res_ccm_best_E_assessment = res_ccm_best_E_assessment %>% rbind(additionnal_df)
    
    
    pb$tick()
    
  }
  
  
  save_file(res_ccm_best_E_summaries, file_save_out_ccm_best_E_and_tp_summaries)
  save_file(res_ccm_best_E_assessment, file_save_out_ccm_best_E_and_tp_assessment)
  
} else {
  
  res_ccm_best_E_summaries = import_file(file_save_out_ccm_best_E_and_tp_summaries)
  # colnames(res_ccm_best_E_summaries) = gsub("^X(\\d+)\\.$", "\\1%", colnames(res_ccm_best_E_summaries))
  res_ccm_best_E_assessment = import_file(file_save_out_ccm_best_E_and_tp_assessment)

}

```

## Plots

```{r plots_ccm}

if (exe_plots) {
           
  
  this_tp = tp_tested_causality[1]
  
  # Single id and causal relationship -> rho depending on lib size
  # this_id = all_ids[12]
  lst_p.fig2a = list()
  lst_p.figS4 = list()
  # this_id.p.fig2aS4 = all_ids[1]
  for (this_id.p.fig2aS4 in ids_single_plots) {
    for (i in 1:length(list_of_causality_tested)) {
      for (this_metric in c("rho", "mae", "rmse")) {
      # for (this_metric in c("rho")) {

        # Plot 1 direction
        this_causal_rel_2aS4 = list_of_causality_tested[[i]]
        this_key = paste0(this_metric, "-", this_causal_rel_2aS4[1], "_to_", this_causal_rel_2aS4[2], "-", this_id.p.fig2aS4)
        p.fig2a = ggplot_convergence_ccm_one_dir(res_ccm_best_E_summaries, this_id.p.fig2aS4,
                                                 this_causal_rel_2aS4, this_tp, labels_of_variables,
                                                 metric = this_metric)
        if (!plots_with_titles) p.fig2a = p.fig2a + labs(title = NULL, subtitle = NULL)
        print(p.fig2a)
        lst_p.fig2a[[this_key]] = p.fig2a

        # Plot both directions on the same plot
        reverse_causal_rel_2aS4 = c(this_causal_rel_2aS4[2], this_causal_rel_2aS4[1])
        if (i < length(list_of_causality_tested)) { # We check if the reverse causality is in the remaining list
          remaining_list = list_of_causality_tested[(i + 1):length(list_of_causality_tested)]
          is_reverse_present_in_remaining = any(sapply(remaining_list, function(x) all(x == reverse_causal_rel_2aS4)))
        } else {
          is_reverse_present_in_remaining = FALSE  # No remaining elements to check
        }
        if (!is_reverse_present_in_remaining) {
          p.figS4 = ggplot_convergence_ccm_two_dir(res_ccm_best_E_summaries, this_id.p.fig2aS4,
                                                   this_causal_rel_2aS4, this_tp, labels_of_variables,
                                                   metric = this_metric)
          if (!plots_with_titles) p.figS4 = p.figS4 + labs(title = NULL, subtitle = NULL)
          print(p.figS4)
          lst_p.figS4[[this_key]] = p.figS4
        }

      }
    }
  }
  
  
  # We remove the stocks where the forecasting skill is always negative (i.e. method_select_E_prefered is not NA if it is positive_range_top_x_percent)
  df_ids_kept_from_E = res_simplex_tp1_summary_opti_E %>% 
    filter(id_timeseries %in% all_ids_plots) %>% 
    filter(!is.na(E_opti_simplex), method_E_opti_simplex == method_select_E_prefered)
  
  print("Number of stocks kept for the causality assessment (for var_lib, i.e. consequence):") 
  print(df_ids_kept_from_E %>% group_by(variable) %>% summarise(n = n()))
  
  
  # Histogram of the causality
  p.fig3 = ggplot_ccm_hist_causality_one_tp(res_ccm_best_E_assessment, this_tp, labels_of_variables, 
                                            list_of_causality_tested = list_of_causality_tested, 
                                            df_ids_kept_from_E = df_ids_kept_from_E)
  if (!plots_with_titles) p.fig3 = p.fig3 + labs(title = NULL, subtitle = NULL)
  print(p.fig3)
  
  # Alluvial diagram of the causality (one tp and check the link between both directions)
  p.figS5a = ggplot_ccm_alluvial_causality_one_tp_both_dir(res_ccm_best_E_assessment, this_tp, labels_of_variables,
                                                          list_of_causality_tested = list_of_causality_tested,
                                                          df_ids_kept_from_E = df_ids_kept_from_E)
  if (!plots_with_titles) p.figS5a = p.figS5a + labs(title = NULL, subtitle = NULL)
  print(p.figS5a)

  # Histograms and flow for multiple tp
  these_tp = tp_tested_causality
  p.figS5b = ggplot_ccm_hist_causality_multiple_tp(res_ccm_best_E_assessment, these_tp, labels_of_variables,
                                                   list_of_causality_tested = list_of_causality_tested,
                                                   df_ids_kept_from_E = df_ids_kept_from_E)
  if (!plots_with_titles) p.figS5b = p.figS5b + labs(title = NULL, subtitle = NULL)
  print(p.figS5b)
  
  p.figS5c = ggplot_ccm_alluvial_causality_multiple_tp(res_ccm_best_E_assessment, these_tp, labels_of_variables,
                                                       list_of_causality_tested = list_of_causality_tested,
                                                       df_ids_kept_from_E = df_ids_kept_from_E)
  if (!plots_with_titles) p.figS5c = p.figS5c + labs(title = NULL, subtitle = NULL)
  print(p.figS5c)

  # At tp with the maximum rho (assess causality if causality for this tp and tp <= 0)
  p.figS5d = ggplot_ccm_hist_causality_tp_max_rho(res_ccm_best_E_assessment, labels_of_variables,
                                                  list_of_causality_tested = list_of_causality_tested,
                                                  df_ids_kept_from_E = df_ids_kept_from_E)
  if (!plots_with_titles) p.figS5d = p.figS5d + labs(title = NULL, subtitle = NULL)
  print(p.figS5d)

  p.figS5e = ggplot_ccm_alluvial_causality_tp_max_rho_both_dir(res_ccm_best_E_assessment, labels_of_variables,
                                                               list_of_causality_tested = list_of_causality_tested,
                                                               df_ids_kept_from_E = df_ids_kept_from_E)
  if (!plots_with_titles) p.figS5e = p.figS5e + labs(title = NULL, subtitle = NULL)
  print(p.figS5e)

  # Compare the methods
  p.figS5f = ggplot_ccm_alluvial_causality_one_tp_and_tp_max_rho(res_ccm_best_E_assessment, this_tp, labels_of_variables,
                                                                 list_of_causality_tested = list_of_causality_tested,
                                                                 df_ids_kept_from_E = df_ids_kept_from_E)
  if (!plots_with_titles) p.figS5f = p.figS5f + labs(title = NULL, subtitle = NULL)
  print(p.figS5f)
  
  # Save the plots
  if (save_plots) {
    for (typ in types_plots) {

      for (this_key_2a in names(lst_p.fig2a)) {
        ggsave(lst_p.fig2a[[this_key_2a]],
               filename = paste0(dir_out, typ, "/fig2a-convergence_ccm_one_dir-", this_key_2a, ".", typ),
               device = typ, width = 5, height = 4)
      }
      for (this_key_S4 in names(lst_p.figS4)) {
        ggsave(lst_p.figS4[[this_key_S4]],
               filename = paste0(dir_out, typ, "/figS4-convergence_ccm_two_dir-", this_key_S4, ".", typ),
               device = typ, width = 5, height = 4)
      }
      
      ggsave(p.fig3, filename = paste0(dir_out, typ, "/fig3-ccm_hist_causality_one_tp.", typ),
             device = typ, width = 5, height = 5)
      ggsave(p.figS5a, filename = paste0(dir_out, typ, "/figS5a-ccm_alluvial_causality_one_tp_both_dir.", typ),
             device = typ, width = 6, height = 4)
      ggsave(p.figS5b, filename = paste0(dir_out, typ, "/figS5b-ccm_hist_causality_multiple_tp.", typ),
             device = typ, width = 8, height = 6)
      ggsave(p.figS5c, filename = paste0(dir_out, typ, "/figS5c-ccm_alluvial_causality_multiple_tp.", typ),
             device = typ, width = 7, height = 10)
      ggsave(p.figS5d, filename = paste0(dir_out, typ, "/figS5d-ccm_hist_causality_tp_max_rho.", typ),
             device = typ, width = 4, height = 5)
      ggsave(p.figS5e, filename = paste0(dir_out, typ, "/figS5e-ccm_alluvial_causality_tp_max_rho_both_dir.", typ),
             device = typ, width = 6, height = 4)
      ggsave(p.figS5f, filename = paste0(dir_out, typ, "/figS5f-ccm_alluvial_causality_one_tp_and_tp_max_rho.", typ),
             device = typ, width = 6, height = 4)
    }
  }
  
}


```



# Assess the strength of the causality

```{r strength_causality}
if (exe_strength_causality) {
  
  cat(" * * * Strength of the causality * * *\n-> assess the strength of the causality\n")
  
  # Prepare the inputs of the mutlivariate S-map
  
  input.selected.strength = data.frame()
  for (k in 1:length(list_of_causality_tested)) {
    
    this_var_cause = list_of_causality_tested[[k]][1] # target in the CCM, but driver/lib in the S-map
    this_var_consequence = list_of_causality_tested[[k]][2] # lib in the CCM, but target in the S-map
    
    for (id in all_ids) {
      
      # E is the optimal embedding dimension from the simplex projection with tp = 1
      this_E = res_simplex_tp1_summary_opti_E %>% 
        filter(id_timeseries == id, variable == this_var_consequence) %>%
        filter(method_E_opti_simplex == method_select_E_prefered) %>%
        pull(E_opti_simplex)
      this_method = method_select_E_prefered
      
      if (is.na(this_E)) { # E with the prefered method can be NA when the forecasting skill is always negative
        this_E = res_simplex_tp1_summary_opti_E %>% 
          filter(id_timeseries == id, variable == this_var_consequence) %>%
          filter(method_E_opti_simplex == method_select_E_default) %>%
          pull(E_opti_simplex)
        this_method = method_select_E_default
      }
      
      tp_with_causality = res_ccm_best_E_assessment %>% 
        filter(id_timeseries == id, var_lib == this_var_consequence, var_target == this_var_cause, causality) %>%
        pull(tp)
      
      input.selected.strength = input.selected.strength %>% rbind(
        data.frame(id_timeseries = id, 
                   var_cause = this_var_cause, var_consequence = this_var_consequence,
                   E = this_E, method_E = this_method, 
                   # tp = 0)
                   tp = tp_tested_causality) %>% # tp is the shift in past of the cause
        filter(tp %in% tp_with_causality) # we only keep the tp with causality
      )
    }
  }
  
  
  # Launch the multivariate S-map to evaluate the strength of causality
  
  res_strength_causality = data.frame()
  res_strength_causality_details_smap = data.frame()
  pb = progress::progress_bar$new(format = "[:bar] :percent eta: :eta", total = nrow(input.selected.strength))
  
  for (i in 1:nrow(input.selected.strength)) {
    
    this_id = input.selected.strength$id_timeseries[i]
    this_var_cause = input.selected.strength$var_cause[i]
    this_var_consequence = input.selected.strength$var_consequence[i]
    this_E = input.selected.strength$E[i]
    this_tp = input.selected.strength$tp[i]
    
    
    # * * * We build the embedding space of dimension E * * *
    # including the cause, the consequence, eventually other significant drivers and the lags of the consequence
    
    this_df = data.frame(time = df[which(df[[name_id_timeseries]] == this_id), name_time])
    
    # We scale the variables
    this_cause_vect_scaled = scale(df[which(df[[name_id_timeseries]] == this_id), this_var_cause])[,1]
    this_consequence_vect_scaled = scale(df[which(df[[name_id_timeseries]] == this_id), this_var_consequence])[,1]
    
    # First dimension = consequence at t
    this_df[[paste0(this_var_consequence, "_t")]] = this_consequence_vect_scaled
    
    # Second dimension = cause at t + this_tp
    if (this_tp == 0) { # actually we don't need to shift the cause
      this_label_cause = paste0(this_var_cause, "_t")
      this_df[[this_label_cause]] = this_cause_vect_scaled
    } else if (this_tp > 0) { # cause -> effect is none sense since the future of the cause (at t+this_tp) affects the consequence (at t)
      this_label_cause = paste0(this_var_cause, "_t_plus_", this_tp)
      this_df[[this_label_cause]] = lead(this_cause_vect_scaled, this_tp)
    } else { # this_tp < 0 i.e. cause -> effect as a delay of abs(this_tp)
      this_label_cause = paste0(this_var_cause, "_t_minus_", abs(this_tp))
      this_df[[this_label_cause]] = lag(this_cause_vect_scaled, abs(this_tp))
    }
    
    # Fill with other drivers if E > 2
    sub_df_these_other_drivers = res_ccm_best_E_assessment %>% 
      filter(id_timeseries == this_id, 
             var_lib == this_var_consequence, var_target != this_var_cause,
             tp == 0, causality)
    if (nrow(sub_df_these_other_drivers) > 0) {
      these_other_drivers = sub_df_these_other_drivers %>% # only drivers with causality at tp = 0
        group_by(var_target) %>%
        filter(max_median_rho_ccm_with_libs == max(max_median_rho_ccm_with_libs)) %>% # keep the E with highest max_rho if multiple E
        ungroup() %>%
        arrange(desc(max_median_rho_ccm_with_libs)) %>% # sort the drivers by max_rho
        pull(var_target)
    } else {
      these_other_drivers = character(0)
    }
    if (length(these_other_drivers) > 0 & this_E > 2) { # If we have enough space in the embedding space and other drivers
      these_added_other_drivers = these_other_drivers[1:min(this_E-2, length(these_other_drivers))]
      if (length(these_added_other_drivers) == 1) { # if only one driver (to avoid the problems while selecting elements in a single element vector)
        this_df[[paste0(these_added_other_drivers, "_t")]] = 
            scale(df[which(df[[name_id_timeseries]] == this_id), these_added_other_drivers])[,1]
      } else {
        for (k in 1:length(these_added_other_drivers)) {
          this_df[[paste0(these_added_other_drivers[k], "_t")]] = 
            scale(df[which(df[[name_id_timeseries]] == this_id), these_added_other_drivers[k]])[,1]
        }
      }
    }
    
    # Fill with lags of the consequence if the embedding space is not full
    if (this_E - 2 - length(these_other_drivers) > 0) {
      for (k in 1:(this_E - 2 - length(these_other_drivers))) {
        this_df[[paste0(this_var_consequence, "_t_minus_", k)]] = lag(this_consequence_vect_scaled, k)
      }
    }
    
    
    this_df = this_df %>% na.omit()
    
    # * * * Compute the multivariate S-map * * *
    out_strength = jacobian_smap(this_df, thetas=seq(0, 20, 0.2), first_column_time=TRUE, 
                                 single_target=paste0(this_var_consequence, "_t"))
    
    
    # * * * Sum up the information for this stock * * *
    these_strength_along_time = out_strength %>% 
      filter(var_cause_jacobian == this_label_cause) %>% 
      na.omit()
    # Mean
    this_mean_strength = mean(these_strength_along_time$value)
    # T-test
    this_t_test = t.test(these_strength_along_time$value)
    this_t_test_stat = this_t_test$statistic
    this_t_test_p_val = this_t_test$p.value
    # Trend
    this_lm_trend = lm(value ~ t, data = these_strength_along_time)
    this_trend_intercept = coef(this_lm_trend)[1]
    this_trend_slope = coef(this_lm_trend)[2]
    this_trend_p_val = summary(this_lm_trend)$coefficients[2,4]
    
    
    
    # * * * Store the results * * *
    res_strength_causality = res_strength_causality %>% rbind(
      data.frame(id_timeseries = this_id, var_cause = this_var_cause, var_consequence = this_var_consequence,
                 E = this_E, tp = this_tp, 
                 this_mean_strength, 
                 this_t_test_stat, this_t_test_p_val, 
                 this_trend_intercept, this_trend_slope, this_trend_p_val)
    )
    res_strength_causality_details_smap = res_strength_causality_details_smap %>% rbind(
      data.frame(id_timeseries = this_id, var_cause = this_var_cause, var_consequence = this_var_consequence,
                 E = this_E, tp = this_tp, 
                 out_strength)
    )
    
    
    pb$tick()
  
  }
  
  save_file(res_strength_causality, file_save_out_strength_causality)
  save_file(res_strength_causality_details_smap, file_save_out_strength_causality_details_smap)
  
} else {
  
  res_strength_causality = import_file(file_save_out_strength_causality)
  res_strength_causality_details_smap = import_file(file_save_out_strength_causality_details_smap)
  
}

```

## Plots
```{r plots_strength_causality_different_examples}

this_tp = 0

# FOR SST -> PROD

id_with_cause_sst_to_prod = res_ccm_best_E_assessment %>% 
  filter(var_lib == "prodbest.div", var_target == "sst.z", tp == 0, causality) %>% 
  pull(id_timeseries) %>% unique()
id_neg_decr_strength_sst_to_prod = res_strength_causality %>% 
  filter(var_cause == "sst.z", var_consequence == "prodbest.div", tp == 0, 
         this_mean_strength < 0, this_t_test_p_val < 0.05,
         this_trend_slope < 0, this_trend_p_val < 0.05) %>%
  pull(id_timeseries) %>% unique()
ids_1 = intersect(id_with_cause_sst_to_prod, id_neg_decr_strength_sst_to_prod)

this_causal_rel = c("sst.z", "prodbest.div")
for (this_id in ids_1) {
  p = ggplot_strength_one_stock(res_strength_causality_details_smap, res_strength_causality, this_id, this_causal_rel, this_tp)
  print(p)
}


# FOR U -> PROD

id_with_cause_u_to_prod = res_ccm_best_E_assessment %>% 
  filter(var_lib == "prodbest.div", var_target == "UdivUmsypref", tp == 0, causality) %>% 
  pull(id_timeseries) %>% unique()
id_neg_decr_strength_u_to_prod = res_strength_causality %>%
  filter(var_cause == "UdivUmsypref", var_consequence == "prodbest.div", tp == 0, 
         this_mean_strength > 0, this_t_test_p_val < 0.05,
         this_trend_slope < 0, this_trend_p_val < 0.05) %>%
  pull(id_timeseries) %>% unique()
ids_2 = intersect(id_with_cause_u_to_prod, id_neg_decr_strength_u_to_prod)

this_causal_rel = c("UdivUmsypref", "prodbest.div")
for (this_id in ids_2) {
  p = ggplot_strength_one_stock(res_strength_causality_details_smap, res_strength_causality, this_id, this_causal_rel, this_tp)
  print(p)
}




```


```{r plots_strength_causality}


if (exe_plots) {
  
  # Single id and causal relationship -> strength depending on time
  
  this_tp = tp_tested_causality[1]
  
  lst_p.fig2b = list()
  # this_id.p.fig2b = all_ids[1]
  for (this_id.p.fig2b in ids_single_plots) {
    for (i in 1:length(list_of_causality_tested)) {
      this_causal_rel_2b = list_of_causality_tested[[i]]
      
      is_causal_rel = res_ccm_best_E_assessment %>% 
        filter(id_timeseries == this_id.p.fig2b, var_lib == this_causal_rel_2b[2], var_target == this_causal_rel_2b[1], tp == this_tp) %>% 
        pull(causality)
      
      if (is_causal_rel) {
        p.fig.2b = ggplot_strength_one_stock(res_strength_causality_details_smap, res_strength_causality, 
                                             this_id.p.fig2b, this_causal_rel_2b, this_tp)
        if (!plots_with_titles) p.fig.2b = p.fig.2b + labs(title = NULL, subtitle = NULL)
        print(p.fig.2b)
        lst_p.fig2b[[paste0(this_causal_rel_2b[1], "_to_", this_causal_rel_2b[2], "-", this_id.p.fig2b)]] = p.fig.2b
      }
      
      
    }
  }

  
  
  # We remove the stocks where the forecasting skill is always negative (i.e. method_select_E_prefered is not NA if it is positive_range_top_x_percent)
  df_ids_kept_from_E = res_simplex_tp1_summary_opti_E %>% 
    filter(id_timeseries %in% all_ids_plots) %>% 
    filter(!is.na(E_opti_simplex), method_E_opti_simplex == method_select_E_prefered)
  
  
  # Summary of the strength of the causality (qualitative analysis)
  p.fig.4 = ggplot_strength_summary(res_strength_causality, res_ccm_best_E_assessment, 
                                    labels_of_variables, this_tp, list_of_causality_tested[1:2],
                                    df_ids_kept_from_E = df_ids_kept_from_E)
  if (!plots_with_titles) p.fig.4 = p.fig.4 + labs(title = NULL, subtitle = NULL)
  print(p.fig.4)
  
  p.fig.S6 = ggplot_strength_summary(res_strength_causality, res_ccm_best_E_assessment, 
                                    labels_of_variables, this_tp, list_of_causality_tested,
                                    df_ids_kept_from_E = df_ids_kept_from_E)
  if (!plots_with_titles) p.fig.S6 = p.fig.S6 + labs(title = NULL, subtitle = NULL)
  print(p.fig.S6)
  
  
  
  # Boxplot strength
  
  df_plot = res_strength_causality %>% rename(E_CCM = E) %>%
    filter(id_timeseries %in% all_ids_plots) %>%
    left_join(res_ccm_best_E_assessment,
              by = c("id_timeseries" = "id_timeseries", "var_cause" = "var_target", "var_consequence" = "var_lib", "tp" = "tp"))
  
  df_plot$kept = TRUE
  for (this_var_consequence in unique(res_strength_causality$var_consequence)) {
    these_ids_kept = df_ids_kept_from_E %>% filter(variable == this_var_consequence) %>% 
      pull(id_timeseries) %>% as.character()
    df_plot = df_plot %>% 
      mutate(kept = ifelse((var_consequence == this_var_consequence) & !(id_timeseries %in% these_ids_kept), 
                           FALSE, kept))
  }

  df_plot = df_plot %>% filter(kept)
  df_plot = df_plot %>%
    left_join(df_plot %>% 
                group_by(var_cause, var_consequence, tp) %>%
                summarise(n = sum(causality), .groups = "drop"),
              by = c("var_cause" = "var_cause", "var_consequence" = "var_consequence", "tp" = "tp")) %>%
    mutate(label_causal_rel = paste0(labels_of_variables[var_cause], "\n->\n", labels_of_variables[var_consequence])) %>%
    mutate(label_causal_rel = paste0(label_causal_rel, "\n(n = ", n, ")")) %>%
    filter(tp == 0, causality)
  
  
  order_labels_causal_rel = c()
  for (i in 1:length(list_of_causality_tested)) {
    this_n = df_plot %>% 
      filter(var_cause == list_of_causality_tested[[i]][1], var_consequence == list_of_causality_tested[[i]][2]) %>% 
      pull(n) %>% unique()
    order_labels_causal_rel = c(order_labels_causal_rel,
                                paste0(labels_of_variables[list_of_causality_tested[[i]][1]], "\n->\n",
                                       labels_of_variables[list_of_causality_tested[[i]][2]], 
                                       "\n(n = ", this_n, ")"))
    
  }
  df_plot = df_plot %>% 
    mutate(label_causal_rel = factor(label_causal_rel, levels = order_labels_causal_rel))

  p.figS7 = ggplot(df_plot, aes(x = label_causal_rel, y = this_mean_strength)) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
    geom_boxplot() +
    labs(x = "Causal relationship", y = "Mean strength of the causality") +
    theme_light()
  if (!plots_with_titles) p.figS7 = p.figS7 + labs(title = NULL, subtitle = NULL)
  print(p.figS7)
  
  
  # Save the plots
  if (save_plots) {
    for (typ in types_plots) {
      
      for (this_key_2b in names(lst_p.fig2b)) {
        ggsave(lst_p.fig2b[[this_key_2b]], 
               filename = paste0(dir_out, typ, "/fig2b-strength_one_stock-", this_key_2b, ".", typ), 
               device = typ, width = 6, height = 4)
      }
      
      ggsave(p.fig.4, filename = paste0(dir_out, typ, "/fig4-strength_summary.", typ), 
             device = typ, width = 7, height = 3.5)
      ggsave(p.fig.S6, filename = paste0(dir_out, typ, "/figS6-strength_summary.", typ), 
             device = typ, width = 7, height = 5)
      ggsave(p.figS7, filename = paste0(dir_out, typ, "/figS7-strength_boxplot.", typ),
             device = typ, width = 8, height = 5)
    }
  }

}

```


# Recap for one stock 

```{r recap_for_one_stock}

causal_rel_test = c("UdivUmsypref", "prodbest.div")

# ids_decreasing_strength = res_strength_causality %>% 
#            filter(tp == 0, var_cause == causal_rel_test[1], var_consequence == causal_rel_test[2],
#                   this_trend_p_val < 0.05, this_trend_slope < 0) %>%
#            pull(id_timeseries)
# 
# ids_clean = res_ccm_best_E_assessment %>% 
#   filter(id_timeseries %in% all_ids_plots) %>%
#   filter(tp == 0, causality, var_lib == causal_rel_test[2], var_target == causal_rel_test[1]) %>%
#   filter(id_timeseries %in% ids_decreasing_strength) %>% 
#   pull(id_timeseries)

ids_clean = c("ANCHMEDGSA6")

for (this_id in ids_clean) {
  
  variables = unique(unlist(list_of_causality_tested))
  
  p1 = ggplot_timeseries_one_stock(df[df[[name_id_timeseries]] == this_id, ], variables, 
                                           labels_of_variables, id = this_id, time = name_time, scale = TRUE)
  print(p1)
  
  p2_rho = ggplot_convergence_ccm_one_dir(res_ccm_best_E_summaries, this_id, causal_rel_test, 0,
                                      labels_of_variables, metric = "rho")
  print(p2_rho)
  p2_mae = ggplot_convergence_ccm_one_dir(res_ccm_best_E_summaries, this_id, causal_rel_test, 0,
                                      labels_of_variables, metric = "mae")
  print(p2_mae)
  p2_rmse = ggplot_convergence_ccm_one_dir(res_ccm_best_E_summaries, this_id, causal_rel_test, 0,
                                      labels_of_variables, metric = "rmse")
  print(p2_rmse)
  
  p3 = ggplot_strength_one_stock(res_strength_causality_details_smap, res_strength_causality, this_id,
                                 causal_rel_test, 0)
  print(p3)
  
}

      
```



# Assess Granger causality

```{r granger_causality}

if (exe_granger_causality) {
  
  # Define the input properly for the causality tested
  df_causality_tested = data.frame()
  for (k in 1:length(list_of_causality_tested)) {
    df_causality_tested = df_causality_tested %>% rbind(
      data.frame(cause = list_of_causality_tested[[k]][1], 
                 consequence = list_of_causality_tested[[k]][2])
    )
  }
  
  # Outputs are stored in these dataframes
  res_granger_causality = data.frame()
  res_granger_causality_detailed = data.frame()
  
  pb = progress::progress_bar$new(format = "[:bar] :percent eta: :eta", 
                                  total = length(all_ids))
  for (id in all_ids) {
    
    this_df = df[which(df[[name_id_timeseries]] == id), c(name_time, unique(unlist(list_of_causality_tested)) ) ]
    
    # Scale the variables
    for (this_var in unique(unlist(list_of_causality_tested))) {
      this_df[[this_var]] = scale(this_df[[this_var]])[,1]
    }
    # Test the Granger causality
    suppressWarnings({
      res_gc = granger_causality_assessment_pair(this_df, causality_tested = df_causality_tested, 
                                                 max_order_tested = 10, silent = TRUE)
    })
    res_granger_causality = res_granger_causality %>% 
      rbind(cbind(id_timeseries = id, res_gc$causality_tested))
    res_granger_causality_detailed = res_granger_causality_detailed %>%
      rbind(cbind(id_timeseries = id, res_gc$causality_tested_detailed))
    
    pb$tick() 
  }
  
  
  save_file(res_granger_causality, file_save_out_granger_causality)
  save_file(res_granger_causality_detailed, file_save_out_granger_causality_details)
  
} else {
  
  res_granger_causality = import_file(file_save_out_granger_causality)
  res_granger_causality_detailed = import_file(file_save_out_granger_causality_details)
  
}

```

## Plots

```{r plots_granger_causality}

if (exe_plots) {
  
  library(ggalluvial)
  
  
  # We remove the stocks where the forecasting skill is always negative (i.e. method_select_E_prefered is not NA if it is positive_range_top_x_percent)
  df_ids_kept_from_E = res_simplex_tp1_summary_opti_E %>% 
    filter(id_timeseries %in% all_ids_plots) %>% 
    filter(!is.na(E_opti_simplex), method_E_opti_simplex == method_select_E_prefered)
  
  # id_removed = res_simplex_tp1_summary_opti_E %>% filter(id_timeseries %in% all_ids_plots) %>% 
  #   filter(is.na(E_opti_simplex), method_E_opti_simplex == method_select_E_prefered) %>% 
  #   pull(id_timeseries) %>% as.character() # we remove the stocks where the forecasting skill is always negative
  
  df_plot = res_granger_causality %>% 
    filter(id_timeseries %in% all_ids_plots) %>% rename(causality_granger = causality) %>%
    left_join(res_ccm_best_E_assessment %>% 
                filter(id_timeseries %in% all_ids_plots, tp == 0) %>% rename(causality_ccm = causality),
              by = c("id_timeseries" = "id_timeseries", "consequence" = "var_lib", "cause" = "var_target")) %>% 
    mutate(label_causal_rel = paste0(labels_of_variables[.[["cause"]]], " -> ", labels_of_variables[.[["consequence"]]]))
  
  df_plot$kept = TRUE
  for (this_var_consequence in unique(res_granger_causality$consequence)) {
    these_ids_kept = df_ids_kept_from_E %>% filter(variable == this_var_consequence) %>% 
      pull(id_timeseries) %>% as.character()
    df_plot = df_plot %>% 
      mutate(kept = ifelse((consequence == this_var_consequence) & !(id_timeseries %in% these_ids_kept), 
                           FALSE, kept))
  }
  
  df_plot = df_plot %>% 
    filter(kept) %>% 
    group_by(label_causal_rel, causality_ccm, causality_granger) %>%
    summarise(n = n()) %>%
    ungroup()
  
  # allivial plot causality ccm granger
  p.figS8 = ggplot(df_plot, aes(axis1 = causality_ccm, axis2 = causality_granger, y = n)) +
    facet_wrap(~ label_causal_rel, scales = "free_y") +
    geom_alluvium(aes(fill = label_causal_rel)) +
    geom_stratum() +
    geom_text(stat = "stratum", aes(label = after_stat(stratum)), size = 2) +
    geom_text(aes(label = n, group = label_causal_rel), stat = "alluvium", size = 3) +
    scale_x_discrete(limits = c("Causality CCM", "Causality Granger"), expand = c(0.1, 0.1)) +
    labs(title = "Comparison of the causality CCM and Granger", x = NULL, y = "Number of stocks") +
    theme_light() +
    theme(legend.position = "none")
    
    
  
  if (save_plots) {
    for (typ in types_plots) {
      ggsave(p.figS8, filename = paste0(dir_out, typ, "/figS8-comparison_causality_ccm_granger.", typ),
             device = typ, width = 7, height = 5)
    }
  }

}

```

